# GitHub Pages configuration for Flowey
title: Flowey
description: A delightful ASCII art tool inspired by cowsay but themed around the beloved Undertale universe
url: "https://lazypwny751.github.io"
baseurl: "/flowey"

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Site settings
author:
  name: "lazypwny751"
  email: "your-email@example.com"

# Navigation
header_pages:
  - index.md
  - installation.md
  - usage.md
  - characters.md
  - contributing.md

# GitHub repository
github:
  repository_url: https://github.com/lazypwny751/flowey
  repository_name: flowey

# Social links
social_links:
  github: lazypwny751

# Enable syntax highlighting
highlighter: rouge
markdown: kramdown

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Include files
include:
  - _pages/
