name: Package Installation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERSION: 1.0.0
  PREFIX: target

jobs:
    mint:
        name: Install on Mint
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Get dependencies and build
            run: |
              sudo apt update
              sudo apt install -y build-essential dpkg-dev
              make PREFIX=${{ env.PREFIX }} VERSION=${{ env.VERSION }} ubuntu

          - name: Install package
            run: |
              sudo apt install ./${{ env.PREFIX }}/flowey-ubuntu_${{ env.VERSION }}_all.deb

          - name: Test installation
            run: |
              flowey --version